### ISSUE TITLE
CSP Not Defined After Latest Changes

### ISSUE THREAD

**Issue by ScottTravisHartley** [pmeenan/cf-workers#1]
The recent commits to the streaming optimizations has an error leading to console warnings in the worker editor. 

// Bypass processing for image requests (for most browsers, Firefox doesn't include image/* on the accept)
  if (!isImage) {
    const url = new URL(event.request.url);
    if (event.request.method === 'GET' && isProxyRequest(url)) {
      // Pass the requests through to the origin server
      // (through the underlying request cache and filtering headers).
      event.respondWith(proxyRequest('https:/' + url.pathname + url.search, csp.request));
    } else {
      event.respondWith(processRequest(event.request, event));
    }
  }
});

CSP is not defined in the above block (around line 37)

**Comment by pmeenan** [comment]
Argh, thanks. I think I did a search for csp and accidentally overwrote where the cursor was at the time. Should be [fixed now](https://github.com/pmeenan/cf-workers/commit/8db8c6a1063c9ac396f743488400b86f6a1dfde8)

**Comment by ScottTravisHartley** [comment]
Yep, looks like it was resolved!
