### ISSUE TITLE
WordPress.com Image Proxy Images 404

### ISSUE THREAD

**Issue by ScottTravisHartley** [pmeenan/cf-workers#2]
The last update that introduced const ENABLE_REWRITE_DOMAINS = true;   doesn't seem to be working correctly atleast when I tested it on a website with wordpress.com's cdn proxying images. 

When I had the domain being proxied all images were returning a 404 and with a CF-Cache-Status: ByPass. 

I attempted reloading the page a few times to no avail so I ended up commenting out the line for wp.com images for now. The rewriting of the urls in the HTML worked as expected but it was an issue with the response returning a 404.

**Comment by pmeenan** [comment]
Do you have a sample site I can take a look at? Doesn't need the worker on it, just something to test against that shows the issue.


________________________________

**Comment by ScottTravisHartley** [comment]
https://www.sertmedia.com/ I will flip the worker switch back on for now for the images

**Comment by pmeenan** [comment]
It's actually easier if you leave it switched off if you don't mind. Then I can test the rewriting in the worker sandbox.


________________________________

**Comment by pmeenan** [comment]
Argh. Should be fixed now. There was a fast-path exit for image requests to bypass the worker logic but it was also bypassing for proxied requests, not just rewriting.

**Comment by ScottTravisHartley** [comment]
Hmm, I updated the script and I flushed NGINX Cahe + Purged the entire CloudFlare cache to no avail. I will try flipping the rewrites off for those images for now.
